### ISSUE TITLE
[question] Stuck the last step of cpp_with_xamarin

### ISSUE THREAD

**Issue by haroon-oxts** [xamarin/mobcat#27]
First off thanks for the tutorial it really did got a long way demystifying the different steps involved to use C++ in Xamarin. Unfortunately I am stuck with one runtime error with the Android build and another with the iOS build. I am working with VS for Mac. Steps to get to my current state were:

1. Cloned this repo, and corrected two issues that were causing errors.
**Xamarin Forms project** - the iOS project referenced images in the csproj file that did not exist in the asset catalog
**MathFuncs project** - The Android project had a missing .so files in the x84 lib folder

2. Compiled the MathFuncs dlls and added them to the nuget package. I just added them in with the nuget CLI tool, I could not verify that the nuget package actually had those dlls within it. Is there a nuget explorer for Mac like there [is for windows?](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) or could I just that same tool to verify a package made with VS for Mac?

3. Add the create nuget package to the consuming Xamarin Forms project, compile and run

4. I get the following errors:

iOS at runtime 
```
System.EntryPointNotFoundException: CreateMyMathFuncsClass
  at at (wrapper managed-to-native) MathFuncs.MyMathFuncsWrapper.CreateMyMathFuncs()
  at MathFuncs.MyMathFuncs..ctor () [0x00006] in /Users/hhaider/Projects/mobcat/samples/cpp_with_xamarin/Sample/Wrapper/MathFuncs/MathFuncs.Shared/MyMathFuncs.cs:11
  at MathFuncsApp.MainPage.OnAppearing () [0x00008] in /Users/hhaider/Projects/mobcat/samples/cpp_with_xamarin/Sample/Consumer/MathFuncsApp/MathFuncsApp/MainPage.xaml.cs:19
  at Xamarin.Forms.Page.SendAppearing () [0x00024] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:316
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidAppear (System.Boolean animated) [0x00025] in <55e20ffeeae44e4d8fcf262393127192>:0
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.3.1.28/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.3.1.28/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at MathFuncsApp.iOS.Application.Main (System.String[] args) [0x00001] in /Users/hhaider/Projects/mobcat/samples/cpp_with_xamarin/Sample/Consumer/MathFuncsApp/MathFuncsApp.iOS/Main.cs:12
```

Android at runtime
```
System.DllNotFoundException: libMathFuncs.so
  at at (wrapper managed-to-native) MathFuncs.MyMathFuncsWrapper.CreateMyMathFuncs()
  at MathFuncs.MyMathFuncs..ctor () [0x00006] in /Users/hhaider/Projects/mobcat/samples/cpp_with_xamarin/Sample/Wrapper/MathFuncs/MathFuncs.Shared/MyMathFuncs.cs:11
  at MathFuncsApp.MainPage.OnAppearing () [0x00008] in /Users/hhaider/Projects/mobcat/samples/cpp_with_xamarin/Sample/Consumer/MathFuncsApp/MathFuncsApp/MainPage.xaml.cs:19
  at Xamarin.Forms.Page.SendAppearing () [0x00024] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:316
  at Xamarin.Forms.Platform.Android.PageRenderer.OnAttachedToWindow () [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:42
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <44fafc2e0f1847ee827456a85a04372d>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.25(intptr,intptr)
```
Log of the console output for Android
```
[Mono] DllImport attempting to load: 'libMathFuncs.so'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[chatty] uid=10061(com.mobcat.MathFuncsApp) identical 1 line
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "libc++_shared.so" not found'.
[Mono] DllImport attempting to load: 'libMathFuncs.so'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so': 'dlopen failed: library "/storage/emulated/0/Android/data/com.mobcat.MathFuncsApp/files/.__override__/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library '/system/lib/libMathFuncs.so': 'dlopen failed: library "/system/lib/libMathFuncs.so" not found'.
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[chatty] uid=10061(com.mobcat.MathFuncsApp) identical 1 line
[Mono] DllImport error loading library 'libMathFuncs.so': 'dlopen failed: library "libc++_shared.so" not found'.
[Mono] DllImport unable to load library 'dlopen failed: library "libc++_shared.so" not found'.
```

Things I have checked:

- I have verified that the simulators are using compatible processors (x84_64 for the android project and an iPhone 8 with 64 bit arm)
- I have made sure that the nuget package being used was actually the one create in step 2 above.

Any help would be appreciate to nudge me in the right direction.

**Comment by mikeparker104** [comment]
Thanks for reporting these issues. The sample and walkthrough have been updated. Please can you let me know if this resolves the Android runtime issues you had experienced. Can you also confirm whether you get the EntryPointNotFound exception when you use the [NuGet package provided in the Artefacts folder](https://github.com/xamarin/mobcat/blob/master/samples/cpp_with_xamarin/Sample/Artefacts/PrepackedNuGets.zip). Be sure to remove the current version from all projects and from the local .nuget cache (~/Users/{user}/.nuget/packages) before re-adding them.

**Comment by haroon-oxts** [comment]
Thanks for the update Mike. I have pulled the latest changes and both the Android and iOS version build and run fine, and I see the math calculation output. I was using the nuget package that you added in with the latest commit, but I have yet to confirm if this works if I build the C++ libraries locally with the updated build script. I'll add a comment in once I test that this afternoon.

I noticed with the build script you have changed the method to compile for the various Android platforms as the old method was was deprecated (i.e. each compiler having its own subdirectory now).  I assume this is the main change you made in that regard?

**Comment by mikeparker104** [comment]
Thanks for confirming Haroon. The primary changes to the build script were to leverage the [prebuilt toolchains](https://developer.android.com/ndk/guides/other_build_systems#overview) rather than the [standalone toolchain](https://developer.android.com/ndk/guides/standalone_toolchain.html) approach for the reason you describe and adding the -static-libstdc++ flag to link with the [LLVM libc++ library](https://developer.android.com/ndk/guides/cpp-support#libc) which is now the only STL available in the NDK. Please do let me know if you are able to successfully compile the libraries using the updated steps.

**Comment by haroon-oxts** [comment]
Ok so the script that you updated now works, even if I am building the native libraries from scratch. I had three follow up questions if you had some time :

1. Could you replicate the work done in your build script with CMake, provided we tell CMake about the platforms and architectures to compile for. This would then give use a single project that could build a C++ library for any of those platform/architecture combinations.
2. Do you have any more information about this 'bait and switch' method that is being used?
3. I understand the change you made to the android NDK part of the script (i.e. using the specific clang compilers for each architecture), but I don't get is what the change is that fixed the iOS error I was getting before:
```
 MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_main'.
    MTOUCH : error MT5213: Duplicate symbol in: /Users/hhaider/Projects/MathFuncsApp/MathFuncsApp.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-12.1/mtouch-cache/libMathFuncs.a(MyMathFuncsTest.o) (Location related to previous error)
    MTOUCH : error MT5213: Duplicate symbol in: /Users/hhaider/Projects/MathFuncsApp/MathFuncsApp.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-12.1/mtouch-cache/x86_64/main.o (Location related to previous error)
    error MT5209 : Native linking error : 1 duplicate symbol for architecture x86_64
    MTOUCH : error MT5202: Native linking failed. Please review the build log.
```

I am now working on the actual project with this same workflow and it seems to be working fine for now!

**Comment by mikeparker104** [comment]
Thanks for confirming you are now able to complete the walkthrough using the newer NDK and for your positive engagement helping to keep our samples up-to-date. In answer to your questions:

1. You can absolutely replace the build script with CMake as part of your build process and continue to work with VS Code using the [CMake Tools extension](https://marketplace.visualstudio.com/items?itemName=vector-of-bool.cmake-tools)
2. [Paul Bett's](https://log.paulbetts.org/author/paul/) does an excellent job of describing[ bait and switch](https://log.paulbetts.org/the-bait-and-switch-pcl-trick/) in his post. My Colleague[ James Montemagno](https://github.com/jamesmontemagno) also touches upon this concept in a guest lecture for Xamarin University on [Using and Developing Plugins for Xamarin](https://youtu.be/aRYB8oTTpTk?t=2039)
3. The only change made to the iOS aspects of the script was to bump the target SDK version from 12.1 to 12.2. The precompiled iOS library, that you were able to use successfully in your project, had not been updated from its original version. There are a number of reasons why you encountered the [MT5212 ](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5212-native-linking-failed-duplicate-symbol-) and [MT5213 ](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5213-duplicate-symbol-in--location-related-to-previous-error) toolchain errors as described in the [mtouch errors documentation](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5xxx-gcc-and-toolchain-error-messages). Adding _-vvvv_ to the additional mtouch build arguments to get a more verbose build log might assist you with further investigation should you encounter this error in future
