### ISSUE TITLE
Settings for native debugging?

### ISSUE THREAD

**Issue by skuskusku** [xamarin/mobcat#28]
Hello everyone,

I have managed to reproduce all the steps from this tutorial first on a MAC and afterwards from scratch on a Windows PC with Visual Studio 2017 alone. However, I can neither debug the native C++ code (from within Visual Studio 2017 on the windows PC) for Android nor for iOS. Can someone shed some light on what debug settings are required for the native libraries and for the managed wrapper assemblies, in order for the debug info to be present when debugging the final app? Is it possible at all? At least the Android project seems to provide the possibility to switch between managed debugging and C++ debugging, but my breakpoints are never hit. I do wonder if the debugging information gets lost, once the native code is wrapped inside the nuget package or maybe when running lipo for the iOS libraries, can someone with more experience verify or falsify this? I have even managed to omit the nuget step and directly use the managed wrappers with a second version of the final app which doesn't use the nuget package created from the wrapper assemblies, but still native debugging from Visual Studio 2017 on Windows doesn't work for me. Can someone shed some light on the different debugging settings for the different platforms that are required for native debugging?

Thanks,

-- 
Stefan

**Comment by mikeparker104** [comment]
[Visual C++ for cross-platform mobile development](https://docs.microsoft.com/visualstudio/cross-platform/visual-cpp-for-cross-platform-mobile-development) is an installable option for Visual Studio (Windows) that enables a unified debugging experience. There are [no immediate plans to add C++ support to Visual Studio for Mac](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-for-mac-is-now-available/#), however there is a suggestion on the [Developer Community site](https://developercommunity.visualstudio.com/idea/486895/c-for-vs-mac.html) for this which is gaining traction and so I'd encourage you to lend your support to it as this will aid in prioritization.
